### ISSUE TITLE
Error: Invalid or unsupported zip format. No END header found

### ISSUE THREAD

**Issue by brandonalexandertong** [brocessing/kirby-webpack#75]
I am getting this error from a clean build when running npm install, it seems like adm-zip is trying to unzip a file but is unable to for some reason. I don't have a very good working knowledge of what is going on behind the scenes here, so I'm unsure what could be the issue.
I'm running node v16.14.2 npm 8.5.0 and php 8.0.1 on Mac OS Catalina 10.15.7

Full (this is halfway through npm install and breaks the entire install):

🕒  [Kirby Updater] Updating...
/Users/tonylambo/Sites/Active/iain-emaline-kirby/node_modules/adm-zip/zipFile.js:107
                        throw new Error(Utils.Errors.INVALID_FORMAT);
                        ^

Error: Invalid or unsupported zip format. No END header found
    at readMainHeader (/Users/tonylambo/Sites/Active/iain-emaline-kirby/node_modules/adm-zip/zipFile.js:107:10)
    at new module.exports (/Users/tonylambo/Sites/Active/iain-emaline-kirby/node_modules/adm-zip/zipFile.js:19:3)
    at new module.exports (/Users/tonylambo/Sites/Active/iain-emaline-kirby/node_modules/adm-zip/adm-zip.js:20:11)
    at GithubDownloader.extractZip (/Users/tonylambo/Sites/Active/iain-emaline-kirby/node_modules/github-download/lib/zip.js:7:13)
    at WriteStream.<anonymous> (/Users/tonylambo/Sites/Active/iain-emaline-kirby/node_modules/github-download/lib/github-download.js:128:18)
    at WriteStream.emit (node:events:526:28)
    at emitCloseNT (node:internal/streams/destroy:138:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! code 1
npm ERR! path /Users/tonylambo/Sites/Active/iain-emaline-kirby
npm ERR! command failed
npm ERR! command sh -c npm run kirby:update

**Comment by benoitbohnke** [comment]
me too..
